# Generated by Django 5.1.1 on 2024-09-27 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='to_do',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='complete',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created_at',
            new_name='created',
        ),
    ]
